# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.18.5


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
x = np.array([50, 27, 31])
print("Memory size of array x: " + str(x.size * x.itemsize) + " bytes.")

Memory size of array x: 24 bytes.


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
null_vector2 = np.zeros(10)
null_vector2[4] = 1
print(null_vector2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
vector1 = np.arange(10, 50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [248]:
print("Vector 1 =\n", vector1, "\n")

vector2 = vector1[::-1]
print("Reverse of vector 1 =\n", vector2)

Vector 1 =
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Reverse of vector 1 =
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
matrix1 = np.arange(0, 9).reshape(3, 3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [251]:
vector_3 = [1, 2, 0, 0, 4, 0]
vector3 = np.nonzero(vector_3)
print("The indices of the on-zero elements of vector 3: \n", vector3)

The indices of the on-zero elements of vector 3: 
 (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [253]:
matrix2 = np.identity(3)
print("A 3x3 identity matrix is that which the diagonal from top-left to bottom-right are 1 and all others are 0:\n", matrix2)

A 3x3 identity matrix is that which the diagonal from top-left to bottom-right are 1 and all others are 0:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [254]:
matrix3 = np.random.random((3, 3, 3))
print(matrix3)

[[[0.49194749 0.78326262 0.57706198]
  [0.1199003  0.7823971  0.89819595]
  [0.48000646 0.70262986 0.76114296]]

 [[0.54409874 0.7355553  0.40557171]
  [0.39584791 0.23835855 0.68378877]
  [0.70709351 0.44828974 0.43363784]]

 [[0.86939588 0.57528571 0.9334813 ]
  [0.44013913 0.00658766 0.53903242]
  [0.71628736 0.92002768 0.35159947]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [257]:
matrix4 = np.random.random((10, 10))
print("10x10 array of random values:\n", matrix4)
print("\nMin: ", matrix4.min())
print("\nMax: ", matrix4.max())


10x10 array of random values:
 [[0.03528819 0.39861819 0.50481756 0.2556616  0.87523948 0.21498478
  0.44402534 0.5062926  0.53168099 0.95801092]
 [0.38916932 0.7466372  0.95278526 0.40495358 0.22700955 0.80754711
  0.17038763 0.34367681 0.55135031 0.02266307]
 [0.8123699  0.35190553 0.48029421 0.95067461 0.54659927 0.08187097
  0.16339679 0.17296077 0.38316491 0.4248163 ]
 [0.75815502 0.60149991 0.81566827 0.88725589 0.30593517 0.89440242
  0.42048179 0.43796846 0.01764647 0.11686965]
 [0.71300895 0.13478564 0.68530447 0.37562697 0.4005811  0.79704318
  0.53722075 0.94223093 0.90401884 0.65343138]
 [0.15886049 0.5845891  0.6587674  0.50298128 0.49757076 0.14683338
  0.36954427 0.92607108 0.52360701 0.73401239]
 [0.34653422 0.43413045 0.59308849 0.27024604 0.81241518 0.64562201
  0.38647983 0.3211576  0.13363476 0.21074496]
 [0.22117066 0.27505412 0.5593549  0.7488219  0.87759574 0.81724838
  0.87622966 0.65378779 0.43579041 0.16538748]
 [0.94678981 0.00493143 0.2717419  0.03143296 0.8

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [259]:
vector4 = np.random.random(30)
print("Random vector of size 30:\n", vector4)
print("\nMean: ", vector4.mean())

Random vector of size 30:
 [0.89814545 0.35259362 0.22699287 0.65515733 0.83099522 0.18794343
 0.40882446 0.63134913 0.98357928 0.87035398 0.40219934 0.65508772
 0.28103312 0.18953306 0.05522688 0.07743539 0.49994868 0.13693055
 0.67720942 0.93064396 0.87231455 0.5833217  0.45030213 0.74562949
 0.88268361 0.72818954 0.73896424 0.23889564 0.56741365 0.06459724]

Mean:  0.5274498226482733


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [276]:
matrix5 = np.ones((8, 8))
print("Original matrix of all ones:\n", matrix5, "\n")
matrix5[1:-1, 1:-1] = 0
print("To change inner values to zeros:\nInput is: 'matrix[columns indexing, rows indexing]'\nFor example:\nFor columns, we index from 1 to -1 and set those equal to zero.\nFor rows we index from 1 to -1 and set those equal to zero.\n")
print(matrix5)    # x[columns indexing, rows indexing]

Original matrix of all ones:
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]] 

To change inner values to zeros:
Input is: 'matrix[columns indexing, rows indexing]'
For example:
For columns, we index from 1 to -1 and set those equal to zero.
For rows we index from 1 to -1 and set those equal to zero.

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [279]:
matrix6 = np.ones((8, 8))
print("Original matrix: \n", matrix6, "\n")
matrix7 = np.pad(matrix6, pad_width=1, mode='constant', constant_values=0)  # self-explainable by parameter inputs
print("New padded matrix: \n", matrix7)

Original matrix: 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]] 

New padded matrix: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [280]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [334]:
matrix8 = np.diag(1+np.arange(4), k=-1)   # numpy.diag(v, k=0): k is the diagonal in question. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.
print(matrix8)                            # not sure why 1+array, need to check more.

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [299]:
matrix9 = np.ones((8, 8))    # gives an 8x8 matrix of all ones
matrix9[::2, 1::2] = 0       # for columns, from beginning to end, in steps of 2 -- for rows, from index 1 to end, in steps of 2 -- replace these with 0.
matrix9[1::2, ::2] = 0       # for columns, from index 1 to end, in steps of 2 -- for rows, from beginning to end, in steps of 2 -- replace these with 0.
print(matrix9)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [332]:

print("The 'shape' tuple gives the lengths of the array dimensions. So this is a 3D matrix, with lengths 6 by 7 by 8.\nWhen 'unravel_index' is used, to find the 100th element, we use the index of 99.\nOur output is the 100th element:")
matrix10 = np.unravel_index(99,(6,7,8))   # numpy.unravel_index(indices, shape, order='C')
print(matrix10)                           # The elements of the shape tuple give the lengths of the corresponding array dimensions.

The 'shape' tuple gives the lengths of the array dimensions. So this is a 3D matrix, with lengths 6 by 7 by 8.
When 'unravel_index' is used, to find the 100th element, we use the index of 99.
Our output is the 100th element:
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [322]:
matrix11 = np.array([[1,0], [0,1]])
print("Original matrix: \n", matrix11, "\n")
matrix12 = np.tile(matrix11, (4,4))           # numpy.tile(A, repetitions)
print("New matrix: \n", matrix12)             # repetitions is the amount along each axis.

Original matrix: 
 [[1 0]
 [0 1]] 

New matrix: 
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [96]:
matrix13 = np.random.random((5,5))
print("Original matrix: \n", matrix13, "\n")
matrix14 = (matrix13 - np.mean(matrix13)) / (np.std(matrix13))
print("New matrix: \n", matrix14)

Original matrix: 
 [[0.80855429 0.3042197  0.32496361 0.70697283 0.9904651 ]
 [0.25357952 0.03047608 0.55602297 0.7086268  0.64041276]
 [0.26913211 0.54824514 0.90908239 0.57581554 0.73358768]
 [0.98313106 0.93196638 0.40506492 0.53787187 0.21639102]
 [0.10792618 0.63647313 0.18898896 0.26456427 0.14515321]] 

New matrix: 
 [[ 1.04213122 -0.72484978 -0.65217165  0.68623157  1.67947189]
 [-0.90227214 -1.68393482  0.15736532  0.6920264   0.45303246]
 [-0.84778226  0.13011501  1.39434034  0.22671035  0.77947906]
 [ 1.65377642  1.47451643 -0.37152959  0.09377135 -1.03256533]
 [-1.41258155  0.43922959 -1.12857091 -0.86378608 -1.28215332]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [323]:
x = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])
print(x)              # don't understand

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [324]:
matrix15 = np.random.random((5, 3))
print("First matrix: \n", matrix15, "\n")

matrix16 = np.random.random((3, 2))
print("Second matrix: \n", matrix16, "\n")

matrix_product = np.dot(matrix15, matrix16)
print("Dot product of these matrices: \n", matrix_product)

First matrix: 
 [[0.27302268 0.82532849 0.63676789]
 [0.97628176 0.06028472 0.69709688]
 [0.47474453 0.99338687 0.80567839]
 [0.12080557 0.10255539 0.12133281]
 [0.13280949 0.76068252 0.1939368 ]] 

Second matrix: 
 [[0.71150578 0.06965699]
 [0.16840179 0.68124737]
 [0.91533123 0.08142134]] 

Dot product of these matrices: 
 [[0.91609754 0.63311729]
 [1.34285671 0.16583221]
 [1.24253418 0.77541087]
 [0.21428408 0.08815962]
 [0.40011142 0.54325466]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [124]:
vector5 = np.arange(20)

vector5[4:8] *= -1     #negated elements BETWEEN 3 and 8, not including 3 and 8.
print(vector5)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [125]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [179]:
Z = np.ones((5,5))

print("Z**Z is legal: \n", Z**Z, "\n")

print("2 << Z >> 2 is illegal. \n Gives: 'TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule safe.'\n")

print("Z <- Z is legal: \n", Z <- Z, "\n")

print("1j*Z is legal: Gives imaginary numbers: \n", 1j*Z, "\n")

print("Z/1/1 is legal: \n", Z/1/1, "\n")

print("Z<Z>Z is illegal. Gives: 'ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()'")

Z**Z is legal: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

2 << Z >> 2 is illegal. 
 Gives: 'TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule safe.'

Z <- Z is legal: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]] 

1j*Z is legal: Gives imaginary numbers: 
 [[0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]] 

Z/1/1 is legal: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

Z<Z>Z is illegal. Gives: 'ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()'


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [192]:
print(np.array(0) / np.array(0), "\n-Gives 'Runtimewarning' that an invalid value is encountered in true_divide.\n")
print(np.array(0) // np.array(0), "\n-Gives 'Runtimewarning' that divide by zero encountered in the floor divide.\n")
print(np.array([np.nan]).astype(int).astype(float), "\n-Corrects the errors above by using nan (instead of integer 0) and gives it as an integer and float?!")

nan 
-Gives 'Runtimewarning' that an invalid value is encountered in true_divide.

0 
-Gives 'Runtimewarning' that divide by zero encountered in the floor divide.

[-9.22337204e+18] 
-Corrects the errors above by using nan (instead of integer 0) and floor divide (instead of true divide)


<ipython-input-192-8398bbedd672>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0), "\n-Gives 'Runtimewarning' that an invalid value is encountered in true_divide.\n")
<ipython-input-192-8398bbedd672>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0), "\n-Gives 'Runtimewarning' that divide by zero encountered in the floor divide.\n")


#### 29. How to round away from zero a float array ? (★☆☆)

In [244]:
matrix17 = np.random.uniform(-20,20,(5,5))   # numpy.random.uniform(low=0.0, high=1.0, size=None)
print("Random 5 by 5 matrix of floats, with minimum value -20 and maximum value 20:\n\n", matrix17, "\n")

matrix18 = np.abs(matrix17)
print("\nFind absolute value so can round properly later:\n\n", matrix18, "\n")

matrix19 = np.ceil(matrix18)  #  numpy.ceil(x) - Return the ceiling of the input, element-wise.
print("\nFind the rounded AWAY from zero using ceiling, ie round up to one above:\n\n", matrix19, "\n")

matrix20 = np.copysign(matrix19, matrix17)  # numpy.copysign(x1, x2,...) - Change the sign of x1 to that of x2, element-wise.
print("\nCopy signs of first matrix to signs of new matrix:\n\n", matrix20)

Random 5 by 5 matrix of floats, with minimum value -20 and maximum value 20:

 [[-10.63295131  16.04372698 -12.51906744   7.79327362 -17.86279846]
 [ -9.36144416  10.79033305  11.60261389 -17.58118904   5.77831448]
 [ -8.39895113  16.82837454   1.98206742   6.39266422  18.40245152]
 [ 12.8498222   18.80363409   8.4150978   13.18000435   7.34134405]
 [ -0.35393157  16.59993243 -18.77573144  -6.44672948   1.59871534]] 


Find absolute value so can round properly later:

 [[10.63295131 16.04372698 12.51906744  7.79327362 17.86279846]
 [ 9.36144416 10.79033305 11.60261389 17.58118904  5.77831448]
 [ 8.39895113 16.82837454  1.98206742  6.39266422 18.40245152]
 [12.8498222  18.80363409  8.4150978  13.18000435  7.34134405]
 [ 0.35393157 16.59993243 18.77573144  6.44672948  1.59871534]] 


Find the rounded AWAY from zero using ceiling, ie round up to one above:

 [[11. 17. 13.  8. 18.]
 [10. 11. 12. 18.  6.]
 [ 9. 17.  2.  7. 19.]
 [13. 19.  9. 14.  8.]
 [ 1. 17. 19.  7.  2.]] 


Copy signs of

#### 30. How to find common values between two arrays? (★☆☆)

In [330]:
"""
numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
Find the intersection of two arrays.
Return the sorted, unique values that are in both of the input arrays."""

matrix21 = ([30, 82, 10])
print(matrix21)

matrix22 = ([20, 150, 10])
print(matrix22)

intersection = np.intersect1d(matrix21, matrix22)
print("The intersection of these two arrays is: ", intersection)

[30, 82, 10]
[20, 150, 10]
The intersection of these two arrays is:  [10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# numpy.testing.suppress_warnings(forwarding_rule='always')
# I don't want to do it because it might ruin this notebook!

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [349]:
print(np.emath.sqrt(-1))    # It seems the emath recognizes imaginary numbers.
print(np.sqrt(-1))          # But without the emath it doesn't.

print("If the above expressions are equal to one another: ", np.sqrt(-1) == np.emath.sqrt(-1))

1j
nan
If the above expressions are equal to one another:  False


<ipython-input-349-62a0698ea7cc>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))          # But without the emath it doesn't.
<ipython-input-349-62a0698ea7cc>:4: RuntimeWarning: invalid value encountered in sqrt
  print("If the above expressions are equal to one another: ", np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [360]:
today = np.datetime64('today', 'D')
print("Today is: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow is: ", tomorrow)

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday was: ", yesterday)

Today is:  2020-12-07
Tomorrow is:  2020-12-08
Yesterday was:  2020-12-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [373]:
all_dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(all_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [390]:
A = random.random((10,10))
B = random.random((10,10))

matrix24 = np.add(A, B, out=B)
print("A + B =\n", matrix24, "\n")

matrix25 = (np.negative(A))/2
print("-A / 2 =\n", matrix25, "\n")

matrix26 = matrix24*matrix25
print("((A+B)*(-A/2)) =\n", matrix26)

A + B =
 [[0.59133877 0.70457218 0.75068211 1.11654479 0.68920183 1.01504609
  0.59810458 1.66451928 0.13503267 1.15696806]
 [0.51473021 1.52712583 0.8929081  1.09737425 0.16931787 1.69657534
  1.76419839 1.01187732 0.67313075 0.23982998]
 [1.45562783 1.38190011 1.78228061 1.38272943 0.8845624  0.86567019
  0.62149222 0.6283907  1.47175421 0.46970083]
 [0.52135258 1.08642288 0.48937412 0.03790749 1.94333771 1.77921893
  1.20949122 1.79918905 1.27524879 0.94655139]
 [0.44254044 1.32812688 0.73679303 1.63795853 0.69787099 1.53953
  0.96016757 0.74482745 0.87057743 0.65704936]
 [0.74882339 0.88795343 0.57971661 1.53937358 1.33663057 0.80237686
  1.01218017 1.63029451 0.27341905 0.20425935]
 [1.00974027 1.43443958 0.80868039 1.23665153 0.387323   1.95587455
  0.52583793 0.67783132 1.12342124 0.96898698]
 [0.99903368 1.12757188 1.096305   0.43425378 0.94318065 0.62427429
  0.75922551 0.98251266 1.2027197  1.85257155]
 [0.82935649 1.62902224 1.51149198 1.05722912 1.10095111 1.28740577
  0.67

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [405]:
matrix27 = random.random((10,10))
print("Random matrix:\n", matrix27, "\n")

print("Floor division:\n", np.floor(matrix27), "\n")
print("Ceiling division:\n", np.ceil(matrix27)-1, "\n")
print("Truncated value of matrix:\n", np.trunc(matrix27), "\n")
print("As integer type:\n", matrix27.astype(int), "\n")
print("Matrix minus matrix modulo 1:\n", matrix27 - matrix27%1)

Random matrix:
 [[0.79192935 0.0925157  0.65003664 0.73136445 0.42836414 0.13195324
  0.7662011  0.22640014 0.86242992 0.24353654]
 [0.58919122 0.85838769 0.31926491 0.24495819 0.48235292 0.63314176
  0.69400818 0.99555668 0.23200829 0.86060516]
 [0.72882103 0.18154249 0.85556898 0.21837689 0.37874183 0.75706239
  0.58026568 0.73371295 0.18050091 0.73676751]
 [0.6751667  0.63703032 0.02208513 0.77945508 0.70248164 0.86008611
  0.95598601 0.37309636 0.33184022 0.48209124]
 [0.43165774 0.37702217 0.91293547 0.81900779 0.2541944  0.11225205
  0.28152258 0.7595292  0.04955938 0.5916099 ]
 [0.43565529 0.96570011 0.36117604 0.76781937 0.89103672 0.31101415
  0.60180665 0.98550324 0.03657133 0.21715874]
 [0.1797163  0.05403254 0.23148182 0.65570419 0.66768432 0.60468644
  0.72371993 0.32288187 0.68625271 0.35257821]
 [0.8249484  0.6951928  0.84421474 0.42556964 0.38217243 0.15354658
  0.03650977 0.23764915 0.5499952  0.35205732]
 [0.31246247 0.22508593 0.96330873 0.16795219 0.15307886 0.35855

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
z = np.zeros((5, 5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=int)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [19]:
z = np.linspace(0, 1, num=11, endpoint=False, dtype=float)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [25]:
z = np.random.random(10)
z = np.sort(z)
print(z)

[0.10839931 0.25679691 0.25848364 0.38664059 0.51778863 0.57657945
 0.59109489 0.59297817 0.82532703 0.94451206]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [27]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [51]:
def tolerance_equal_array(a,b):
    equal = np.allclose(a,b)
    print(equal)

def notolerance_equal_array(a,b):
    equal = np.array_equal(a,b)
    print(equal)
    
    
a = np.random.random()
b = np.random.random()

tolerance_equal_array(a,b)
notolerance_equal_array(a,b)


False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [65]:
z = np.arange(10)
z.flags.writeable = False   #set writeable to false
print(z)
z[0] = 1                    #attempt to change first value in array returns ValueError for read-only array

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [92]:
def cartesian_to_polar(z):
    x,y = z[:,0], z[:,1]
    r = np.sqrt((x**2)+(y**2))
    print("Pole/distance is", r)
    if x.all() > 0:
        theta = np.arctan(x/y)
        print("Theta is: ", theta)
    elif x.all() < 0:
        theta = np.arctan((y/x)+np.pi)
        print("Theta is: ", theta)
        
z = np.random.random((10,2))
cartesian_to_polar(z)

Pole/distance is [0.84337181 1.14913323 0.71255958 0.78284738 0.9977526  0.97293401
 0.0652266  0.7973924  0.87601167 0.87023464]
Theta is:  [0.1984374  0.56288586 0.68163078 1.20596108 0.77005757 0.13182907
 1.31246073 0.06940702 1.4425105  1.08467752]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [96]:
z = np.random.random(10)
np.argmax(z)

2

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [128]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [158]:
def cauchy_matrix(x,xsize,y,ysize):
    x = np.random.random(xsize)
    y = np.random.random(ysize)
    cauchy = 1.0 / np.subtract.outer(x,y)
    return cauchy

cauchy_matrix(x,8,y,8)

array([[ -1.74167038,   5.6566466 ,  -3.82106557,   4.47048339,
          6.87055928,  -1.98361712,  15.65759009,  -2.98725797],
       [ -1.48532618,  12.87136327,  -2.77163061,   8.02580329,
         21.52517851,  -1.65776754, -28.38929288,  -2.30496276],
       [ -1.49082511,  12.47269247,  -2.7908394 ,   7.86897077,
         20.43296434,  -1.66462034, -30.5425161 ,  -2.31823213],
       [ -1.743622  ,   5.6361577 ,  -3.83047175,   4.45767663,
          6.84035647,  -1.98614901,  15.50160679,  -2.99300385],
       [ -4.79889741,   1.84310244,   9.60862594,   1.69644   ,
          1.95568873,  -7.2280818 ,   2.32749186,  32.2319637 ],
       [ -1.40123906,  26.81645327,  -2.492524  ,  11.8769344 ,
        165.12786213,  -1.55370652, -13.22299072,  -2.1086023 ],
       [ 18.25315885,   1.24111104,   2.72301944,   1.17283349,
          1.29116383,   8.01173266,   1.44339034,   3.39914831],
       [ -1.71840979,   5.91676523,  -3.71086404,   4.63139769,
          7.25812429,  -1.9535009

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [191]:
ii8 = np.iinfo(np.int8)
print(ii8)

ii16 = np.iinfo(np.int16)
print(ii16)
fi16 = np.finfo(np.float16)
print(fi16)

ii32 = np.iinfo(np.int32)
print(ii32)
fi32 = np.finfo(np.float32)
print(fi32)

ii64 = np.iinfo(np.int64)
print(ii64)
fi64 = np.finfo(np.float64)
print(fi64)

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for float32
----

#### 49. How to print all the values of an array? (★★☆)

In [199]:
import sys as sys
np.set_printoptions(threshold=sys.maxsize)
z = np.random.random(1000)
print(z)

[1.61831359e-01 7.80540902e-01 8.38268390e-01 8.18091623e-01
 1.94300847e-01 8.06393659e-01 1.75572554e-02 4.23358846e-01
 8.92372672e-01 8.81683683e-02 5.33355506e-01 9.97893259e-01
 1.02553160e-01 4.99632411e-01 9.49609657e-02 1.05463201e-01
 9.35471641e-01 7.04056062e-01 4.86032783e-01 3.78528526e-01
 7.57797789e-01 7.56414979e-01 4.27992980e-01 4.11705265e-01
 3.05333701e-01 9.17479319e-02 6.49724307e-01 6.27552166e-01
 8.16278615e-01 4.85978438e-01 5.92265315e-01 9.68253503e-01
 5.90365481e-01 7.83584782e-01 7.94799343e-01 2.88971331e-01
 1.55254422e-01 4.54514461e-01 2.07075299e-01 8.83426113e-01
 7.62129549e-01 2.80305624e-01 7.96584442e-02 4.56882304e-01
 5.19971239e-01 7.03323114e-01 5.30887650e-01 4.58350834e-01
 6.74624883e-01 5.66185253e-01 8.06032683e-01 6.10882782e-01
 6.41914461e-01 3.20154021e-02 5.94904022e-01 9.06835727e-01
 8.30339639e-01 9.75547981e-01 6.55420546e-01 1.66290316e-01
 9.71594846e-01 3.57659321e-01 1.72281837e-01 8.30879826e-01
 3.32918291e-01 3.538602

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [216]:
def find_closest_value(x, v):
    v = float()
    x = np.array(x)
    index = np.abs(x-v).argmin()
    return z[index]

b = np.random.random(11)
print("Vector: \n", b)
c = 2
print("\nGiven Scalar: \n", c)
print("\nClosest value to the given scalar in array: \n", find_closest_value(b,c))

Vector: 
 [0.77120725 0.15596659 0.02566069 0.53716417 0.72116437 0.52456857
 0.20681952 0.31353844 0.81782298 0.33412591 0.81280862]

Given Scalar: 
 2

Closest value to the given scalar in array: 
 0.838268390286982


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [287]:
def position_color(position, color):
    position = np.array(position)
    color = np.array(color)

    print("(x,y): ", position, "\n(r,g,b): ", color)
    x = np.hstack((position,color))
    print("Merged array: ", x)
    
position_color((3,2),(4,2,6))

a = np.random.random(8)
b = np.random.random(3)
position_color(a,b)

a0 = np.zeros(10)
b0 = np.zeros(3)
position_color(a0, b0)

(x,y):  [3 2] 
(r,g,b):  [4 2 6]
Merged array:  [3 2 4 2 6]
(x,y):  [0.85851898 0.27127113 0.72540017 0.39812172 0.37892917 0.68180018
 0.16824638 0.18021019] 
(r,g,b):  [0.38184926 0.90571536 0.16349242]
Merged array:  [0.85851898 0.27127113 0.72540017 0.39812172 0.37892917 0.68180018
 0.16824638 0.18021019 0.38184926 0.90571536 0.16349242]
(x,y):  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
(r,g,b):  [0. 0. 0.]
Merged array:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)