In [1]:
import numpy as np

In [5]:
a = np.arange(10)
print(a)
b = a[2:7:2] 
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [6]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
x[1:4,1:3] = 0  # x[columns indexing, rows indexing]
print(x)

[[0 1 2]
 [3 0 0]
 [6 0 0]
 [9 0 0]]


In [14]:
np.shape([3,2])

(2,)

In [15]:
0.57138545 * 0.92043661

0.5259240866013245